"""create_initial_tables

Revision ID: fd80b7ede9aa
Revises:
Create Date: 2026-03-08 17:05:26.678692

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd80b7ede9aa"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("salt", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_users_id"), "users", ["id"], unique=False, schema="scron"
    )
    op.create_index(
        op.f("ix_scron_users_username"),
        "users",
        ["username"],
        unique=True,
        schema="scron",
    )
    op.create_table(
        "job_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("script_content", sa.Text(), nullable=False),
        sa.Column("script_type", sa.String(length=20), nullable=False),
        sa.Column("default_cron", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["scron.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_job_templates_id"),
        "job_templates",
        ["id"],
        unique=False,
        schema="scron",
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("script_content", sa.Text(), nullable=False),
        sa.Column("script_type", sa.String(length=20), nullable=False),
        sa.Column("cron_expression", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("depends_on", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["scron.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scron",
    )
    op.create_index(
        "ix_jobs_user_active",
        "jobs",
        ["user_id", "is_active"],
        unique=False,
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_jobs_user_id"), "jobs", ["user_id"], unique=False, schema="scron"
    )
    op.create_table(
        "notification_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("telegram_enabled", sa.Boolean(), nullable=False),
        sa.Column("telegram_chat_id", sa.String(length=100), nullable=True),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("notify_on", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["scron.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_notification_settings_id"),
        "notification_settings",
        ["id"],
        unique=False,
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_notification_settings_user_id"),
        "notification_settings",
        ["user_id"],
        unique=False,
        schema="scron",
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["scron.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_refresh_tokens_id"),
        "refresh_tokens",
        ["id"],
        unique=False,
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_refresh_tokens_token"),
        "refresh_tokens",
        ["token"],
        unique=True,
        schema="scron",
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["scron.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_tags_id"), "tags", ["id"], unique=False, schema="scron"
    )
    op.create_index(
        op.f("ix_scron_tags_user_id"), "tags", ["user_id"], unique=False, schema="scron"
    )
    op.create_index(
        "ix_tags_user_name", "tags", ["user_id", "name"], unique=True, schema="scron"
    )
    op.create_table(
        "job_env_vars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("var_key", sa.String(length=200), nullable=False),
        sa.Column("encrypted_value", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["scron.jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scron",
    )
    op.create_index(
        "ix_job_env_vars_job_key",
        "job_env_vars",
        ["job_id", "var_key"],
        unique=True,
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_job_env_vars_id"),
        "job_env_vars",
        ["id"],
        unique=False,
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_job_env_vars_job_id"),
        "job_env_vars",
        ["job_id"],
        unique=False,
        schema="scron",
    )
    op.create_table(
        "job_executions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("log_output", sa.Text(), nullable=True),
        sa.Column("script_version_id", sa.Integer(), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["scron.jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scron",
    )
    op.create_index(
        "ix_job_executions_job_started",
        "job_executions",
        ["job_id", "started_at"],
        unique=False,
        schema="scron",
    )
    op.create_index(
        "ix_job_executions_status",
        "job_executions",
        ["status"],
        unique=False,
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_job_executions_id"),
        "job_executions",
        ["id"],
        unique=False,
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_job_executions_job_id"),
        "job_executions",
        ["job_id"],
        unique=False,
        schema="scron",
    )
    op.create_table(
        "job_script_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("script_content", sa.Text(), nullable=False),
        sa.Column("script_type", sa.String(length=20), nullable=False),
        sa.Column("change_summary", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["scron.jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scron",
    )
    op.create_index(
        "ix_job_script_versions_job_ver",
        "job_script_versions",
        ["job_id", "version"],
        unique=True,
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_job_script_versions_id"),
        "job_script_versions",
        ["id"],
        unique=False,
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_job_script_versions_job_id"),
        "job_script_versions",
        ["job_id"],
        unique=False,
        schema="scron",
    )
    op.create_table(
        "job_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["scron.jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["scron.tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scron",
    )
    op.create_index(
        "ix_job_tags_job_tag",
        "job_tags",
        ["job_id", "tag_id"],
        unique=True,
        schema="scron",
    )
    op.create_index(
        op.f("ix_scron_job_tags_id"), "job_tags", ["id"], unique=False, schema="scron"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scron_job_tags_id"), table_name="job_tags", schema="scron")
    op.drop_index("ix_job_tags_job_tag", table_name="job_tags", schema="scron")
    op.drop_table("job_tags", schema="scron")
    op.drop_index(
        op.f("ix_scron_job_script_versions_job_id"),
        table_name="job_script_versions",
        schema="scron",
    )
    op.drop_index(
        op.f("ix_scron_job_script_versions_id"),
        table_name="job_script_versions",
        schema="scron",
    )
    op.drop_index(
        "ix_job_script_versions_job_ver",
        table_name="job_script_versions",
        schema="scron",
    )
    op.drop_table("job_script_versions", schema="scron")
    op.drop_index(
        op.f("ix_scron_job_executions_job_id"),
        table_name="job_executions",
        schema="scron",
    )
    op.drop_index(
        op.f("ix_scron_job_executions_id"), table_name="job_executions", schema="scron"
    )
    op.drop_index(
        "ix_job_executions_status", table_name="job_executions", schema="scron"
    )
    op.drop_index(
        "ix_job_executions_job_started", table_name="job_executions", schema="scron"
    )
    op.drop_table("job_executions", schema="scron")
    op.drop_index(
        op.f("ix_scron_job_env_vars_job_id"), table_name="job_env_vars", schema="scron"
    )
    op.drop_index(
        op.f("ix_scron_job_env_vars_id"), table_name="job_env_vars", schema="scron"
    )
    op.drop_index("ix_job_env_vars_job_key", table_name="job_env_vars", schema="scron")
    op.drop_table("job_env_vars", schema="scron")
    op.drop_index("ix_tags_user_name", table_name="tags", schema="scron")
    op.drop_index(op.f("ix_scron_tags_user_id"), table_name="tags", schema="scron")
    op.drop_index(op.f("ix_scron_tags_id"), table_name="tags", schema="scron")
    op.drop_table("tags", schema="scron")
    op.drop_index(
        op.f("ix_scron_refresh_tokens_token"),
        table_name="refresh_tokens",
        schema="scron",
    )
    op.drop_index(
        op.f("ix_scron_refresh_tokens_id"), table_name="refresh_tokens", schema="scron"
    )
    op.drop_table("refresh_tokens", schema="scron")
    op.drop_index(
        op.f("ix_scron_notification_settings_user_id"),
        table_name="notification_settings",
        schema="scron",
    )
    op.drop_index(
        op.f("ix_scron_notification_settings_id"),
        table_name="notification_settings",
        schema="scron",
    )
    op.drop_table("notification_settings", schema="scron")
    op.drop_index(op.f("ix_scron_jobs_user_id"), table_name="jobs", schema="scron")
    op.drop_index("ix_jobs_user_active", table_name="jobs", schema="scron")
    op.drop_table("jobs", schema="scron")
    op.drop_index(
        op.f("ix_scron_job_templates_id"), table_name="job_templates", schema="scron"
    )
    op.drop_table("job_templates", schema="scron")
    op.drop_index(op.f("ix_scron_users_username"), table_name="users", schema="scron")
    op.drop_index(op.f("ix_scron_users_id"), table_name="users", schema="scron")
    op.drop_table("users", schema="scron")
    # ### end Alembic commands ###
