apiVersion: apps/v1
kind: Deployment
metadata:
  name: scron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scron
  template:
    metadata:
      labels:
        app: scron
    spec:
      containers:
        - name: app
          image: ghcr.io/krishnarajt/scron:git-c76c6e3e72aea34c25db0ff7c7f9a7362b67163f
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http

          envFrom:
            - secretRef:
                name: scron-env

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
