apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scron-env
  namespace: scron
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: scron-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/scron/scron/env
